version: "3.9"
services:
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - servervol:/serverdata
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - clientvol:/clientdata
volumes:
  servervol:
  clientvol:
networks:
  default:
    external: true
    name: alpine-net
